"""SQLModel table definitions.

Tables:
  M0:  Setting                                — small key/value runtime flags
  M1+: Conversation / Message / Job / Image   — full chat + workflow history
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel

# ---------------------------------------------------------------------------
# M0 — Setting
# ---------------------------------------------------------------------------


class Setting(SQLModel, table=True):
    """Generic key/value store for small JSON-encoded settings.

    Examples: ``system_prompt_version``, ``last_selected_workflow``,
    ``ui_theme``. The big LLM/ComfyUI settings live in config.json —
    Setting is for things that change at runtime.
    """

    key: str = Field(primary_key=True, max_length=128)
    value: str  # JSON-encoded
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# M1 — Chat core
# ---------------------------------------------------------------------------


class Conversation(SQLModel, table=True):
    """A chat session with the LLM.

    `default_workflow_id` is the workflow used when the user doesn't override
    per-message. `default_params` are JSON-encoded Anima args (only the keys
    we override; missing keys fall back to v2mini defaults).
    """

    id: str = Field(primary_key=True, max_length=32)
    title: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    default_workflow_id: str = "local/anima-txt2img-aesthetic-lora"
    default_params: Optional[str] = None  # JSON-encoded dict


class Message(SQLModel, table=True):
    """A single message in a conversation.

    role:
        "user"      — typed by the human
        "assistant" — generated by the LLM (may include reasoning + content)
        "system"    — tool results / internal notes (rarely shown)

    reasoning:
        LLM thinking trace (DeepSeek-R1 / Claude extended thinking).
        Persisted so users can revisit the reasoning behind a generation.

    job_id:
        When this assistant message is tied to a generated image job,
        the resolved Job.id. Multiple Jobs possible for a single message
        (e.g. multi-batch generation).
    """

    id: str = Field(primary_key=True, max_length=32)
    conversation_id: str = Field(max_length=32, index=True)
    role: str = Field(max_length=16)
    content: str
    reasoning: Optional[str] = None
    job_id: Optional[str] = Field(default=None, max_length=32)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# M1 — Job / Image (filled by Step 3)
# ---------------------------------------------------------------------------


class Job(SQLModel, table=True):
    """One ComfyUI execution.

    State machine: PENDING → RUNNING → SUCCEEDED / FAILED / CANCELLED.

    fields encoded as JSON strings (not native dicts) because SQLite
    doesn't have great JSON type support and we want minimal migration
    complexity in M1 — moving to native dicts / JSONB at M2+ is fine.
    """

    id: str = Field(primary_key=True, max_length=32)
    conversation_id: str = Field(max_length=32, index=True)
    message_id: Optional[str] = Field(default=None, max_length=32, index=True)
    queue_item_id: Optional[str] = Field(default=None, max_length=32, index=True)
    prompt_id: Optional[str] = Field(default=None, max_length=64)
    workflow_id: str = Field(max_length=128)
    injector_mode: str = Field(default="v2mini", max_length=16)
    args_snapshot: str  # JSON-encoded dict
    state: str = Field(default="pending", max_length=16)
    error: Optional[str] = None
    source: str = Field(default="single", max_length=16)  # "single" | "queue"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    finished_at: Optional[datetime] = None


class Image(SQLModel, table=True):
    """One generated image tied to a Job.

    A Job can produce multiple Images (batch_size > 1, or queue items).
    """

    id: str = Field(primary_key=True, max_length=32)
    job_id: str = Field(max_length=32, index=True)
    file_path: str  # relative to backend runtime/outputs
    width: int
    height: int
    seed: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# M1 — Queue (filled by Step 4)
# ---------------------------------------------------------------------------


class JobQueue(SQLModel, table=True):
    """A serial queue of Jobs (``enqueue_scene_list`` tool call).

    State machine: pending → running ↔ paused → completed / cancelled / failed.

    `title` is a human-friendly label like "依次生成三个场景".
    """

    id: str = Field(primary_key=True, max_length=32)
    conversation_id: str = Field(max_length=32, index=True)
    workflow_id: str = Field(max_length=128)
    state: str = Field(default="pending", max_length=16)
    title: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    finished_at: Optional[datetime] = None


class JobQueueItem(SQLModel, table=True):
    """One slot in a JobQueue.

    Each item carries its own prompt + args (independent of the LLM's
    later modifications). When picked up, an item becomes a Job whose
    `queue_item_id` points back here.
    """

    id: str = Field(primary_key=True, max_length=32)
    queue_id: str = Field(max_length=32, index=True)
    order_index: int = 0
    scene_label: Optional[str] = None
    prompt_11: str
    prompt_12: str
    args: str  # JSON-encoded dict
    state: str = Field(default="pending", max_length=16)  # pending / running / done / failed / skipped
    job_id: Optional[str] = Field(default=None, max_length=32)
    error: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    finished_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# M2 — Custom workflows (filled later)
# ---------------------------------------------------------------------------


class Workflow(SQLModel, table=True):
    """An imported ComfyUI workflow JSON.

    `source` = "v2mini" (built-in) or "custom" (user-imported).
    `file_path` is where the original JSON lives on disk.
    `raw_json` is an optional inline cache for small workflows.
    """

    id: str = Field(primary_key=True, max_length=32)
    name: str = Field(max_length=64)
    source: str = Field(default="custom", max_length=16)
    file_path: Optional[str] = None
    raw_json: Optional[str] = None  # JSON-encoded, optional cache
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PromptNodeMapping(SQLModel, table=True):
    """Which CLIPTextEncode nodes to inject prompts into for a workflow."""

    id: str = Field(primary_key=True, max_length=32)
    workflow_id: str = Field(max_length=32, unique=True)
    positive_node_id: str = Field(max_length=16)
    positive_node_title: Optional[str] = None
    negative_node_id: Optional[str] = Field(default=None, max_length=16)
    negative_node_title: Optional[str] = None